### ISSUE TITLE
What does targeted mean in graph attack?

### ISSUE THREAD

**Issue by Sutongtong233** [DSE-MSU/DeepRobust#113]
What is the definition of **targeted attack**? For graph data, the target can represent two things:
- target node: attack specific node (in node classification task)
- target label: attack node to be classified as a specific label
While the second is more prevalent. For nettack, as I understand, it means target node, not target label. I hope there is some description of targeted here mean.
Thanks in advance.

**Comment by EdisonLeeeee** [comment]
Hi, @Sutongtong233 

According to [1][2], a targeted attack typically refers to an instance-specific attack, where an instance can be a node in node classification attack, a link in link prediction task, or a graph in graph classification task.

+ [1] [A Survey of Adversarial Learning on Graphs](https://arxiv.org/abs/2003.05730)
+ [2] [Adversarial Attack and Defense on Graph Data: A Survey](https://arxiv.org/abs/1812.10528)

**Comment by ChandlerBang** [comment]
@EdisonLeeeee 's answer is correct. Following the setting in nettack, we typically refer target to target instances.

You can also find a definition in this survey [1]:

![image](https://user-images.githubusercontent.com/32392709/186059672-47060687-9bbe-48f5-88f2-8904462b6da8.png)

 
[1] Adversarial Attacks and Defenses on Graphs: A Review, A Tool and Empirical Studies.
