### ISSUE TITLE
Attacking Custom Pytorch Geometric Implementation GAT using Mettack

### ISSUE THREAD

**Issue by akul-goyal** [DSE-MSU/DeepRobust#116]
Hi,

I am interested in attacking my own GAT model that I coded using Pytorch Geometric. Given the sizes of the graphs, I can use only mettack.py to create a global attack against my model. However, currently, the code seems to be formatted for only GCN based on this [function](https://github.com/DSE-MSU/DeepRobust/blob/e737166fe2fe706c79c2a435e08a3e2853d6b72e/deeprobust/graph/global_attack/mettack.py#L233). Is there a way for mettack to be used against a custom model? If so, how would one go about doing so? Would it be as easy as changing [this](https://github.com/DSE-MSU/DeepRobust/blob/e737166fe2fe706c79c2a435e08a3e2853d6b72e/deeprobust/graph/global_attack/mettack.py#L281) to get the hidden values from the trained model we are trying to attack?

**Comment by EdisonLeeeee** [comment]
Hi, @akul-goyal 

It is not straightforward to use surrogate models other than gcn in metattack. Specifically, you need a lot of work to achieve this:
+ Design your own model (gat) https://github.com/DSE-MSU/DeepRobust/blob/e737166fe2fe706c79c2a435e08a3e2853d6b72e/deeprobust/graph/global_attack/mettack.py#L193-L217
+ Implement the training process for your model
https://github.com/DSE-MSU/DeepRobust/blob/e737166fe2fe706c79c2a435e08a3e2853d6b72e/deeprobust/graph/global_attack/mettack.py#L233-L271
+ Rewrite the function that calculates the meta gradient
https://github.com/DSE-MSU/DeepRobust/blob/e737166fe2fe706c79c2a435e08a3e2853d6b72e/deeprobust/graph/global_attack/mettack.py#L273-L308

**Comment by akul-goyal** [comment]
Thanks for the response. Would it be possible to attack a custom PyTorch GAT model using the [topology](https://github.com/DSE-MSU/DeepRobust/blob/master/deeprobust/graph/global_attack/topology_attack.py) attack?

Thanks,
Akul
