### ISSUE TITLE
Incompatible with latest scipy

### ISSUE THREAD

**Issue by Leirunlin** [DSE-MSU/DeepRobust#124]
Hi! 
I encountered an error when running an attack demo:
`` No module named 'scipy.sparse.linalg.eigen.arpack'; 'scipy.sparse.linalg.eigen' is not a package.``
 
The error occurs as some of the files, such as "deeprobust/graph/rl/env.py",  are not compatible with the latest scipy version.

A solution would be use 
``from scipy.sparse.linalg import eigsh`` instead of ``from scipy.sparse.linalg.eigen.arpack import eigsh`` .
I'm not sure if the problem occurs in other parts of the library or not. Would any updates about it be possible?

**Comment by ChandlerBang** [comment]
Thanks. We actually fixed this issue in this commit [#bbda3f284e8d5a17a4dbe6e11ef2f8f830f1ddd1 ](https://github.com/DSE-MSU/DeepRobust/commit/76d8c133f0e9dee359cbe8be610b209e7e02e151)

**Comment by FinAminToastCrunch** [comment]
Please put my fix in the pip install wheel so that users do not get the scipy import statement incorrect.

**Comment by ChandlerBang** [comment]
Thank you for the reminder. I have updated the pip wheel and you can install it via `pip install deeprobust==0.2.6`.

**Comment by Leirunlin** [comment]
Thanks for your update!
