### ISSUE TITLE
url for PrePtbDataset is not valid

### ISSUE THREAD

**Issue by greendimple** [DSE-MSU/DeepRobust#159]
The url for the PrePtbDataset  which begins with "https://raw.githubusercontent.com/ChandlerBang/Pro-GNN" is no longer valid.
Where can I find the perturbed datasets?

**Comment by greendimple** [comment]
This happens to attack_method="nettack".
Searching https://[raw.githubusercontent.com/ChandlerBang/Pro-GNN/master/nettack/cora_nettack_adj_005.npz] (https://raw.githubusercontent.com/ChandlerBang/Pro-GNN/master/nettack/cora_nettack_adj_005.npz) won't download the packet.

**Comment by ChandlerBang** [comment]
Hi, for Nettack, the ratio should not be 0.05. Instead, it should be 1, 2, 3, 4, or 5 as shown below.

![image](https://github.com/user-attachments/assets/60375518-6461-429f-ae32-c06a35d62526)
