### ISSUE TITLE
中文介绍文章

### ISSUE THREAD

**Issue by zhusleep** [DSE-MSU/DeepRobust#17]
参加KDD的图数据攻防比赛开始熟悉这个包，里面有很多不错的代码。我写了篇中文介绍的文章。
https://zhuanlan.zhihu.com/p/148282580

另外pytorch 不支持对稀疏矩阵的求导。可以通过矩阵分解的方式实现稀疏矩阵下增加节点的梯度计算。如果这里面直接支持就好了。

**Comment by ChandlerBang** [comment]
谢谢你的文章和建议，我们会继续努力改进这个工具包的！

Thank you for your interest and suggestions! We will keep improving our repository - so stay tuned!
