### ISSUE TITLE
Refactor attack method for DICE, IGAttack, Random, PGDAttack, MinMax

### ISSUE THREAD

**Issue by HenryKenlay** [DSE-MSU/DeepRobust#22]
The classes  `DICE`, `IGAttack`, `Random`, `PGDAttack`, `MinMax` all subclass `BaseAttack` however the `BaseAttack.attack` method doesn't specify any arguments. I plan to refactor in the following ways:

- Move arguments common to multiple attacks (such as `labels`) into the `BaseAttack` class.
- Make some variable names more consistent (i.e., use just `adj` or just `ori_adj`).
- Add documentation to the `BaseAttack` class describing the variables and accepted types (this can be rewritten once you decide on documentation conventions)
- Add `**kwargs` to all subclasses (this would allow one to use different classes attack method in the same way)

I think organising the classes in `mettack.py` can be a separate issue because things seem slight differently there (the attack classes subclass the intermediate class `BaseMeta`). 

Before I get started I would be interested in your answers to the following:
+ Do you prefer the convention `ori_adj` and `ori_features` or `adj` and `features`? 
+ Do you prefer `perturbations` or `n_perturbations`?

As an aside I'm going to put in a PR to remove unused imports for all files in `deeprobust.graph.global_attack`, I hope that's ok :)

**Comment by ChandlerBang** [comment]
I would suggest `ori_adj`, `ori_features` and `n_perturbations`. But when refactoring,  you might need to pay attention to the situation where `adj` and `ori_adj`  both exist in the same function (I am not sure whether this did happen; but we need to be careful). 

You can go ahead and thank you so much : )

**Comment by HenryKenlay** [comment]
Thanks for the heads up, at least in the `attack` methods I looked at this wasn't the case!
