### ISSUE TITLE
Another attack to graph-based ML method

### ISSUE THREAD

**Issue by binghuiwang** [DSE-MSU/DeepRobust#24]
Attacking graph-based classification via manipulating the graph structure, CCS'19.

**Comment by ChandlerBang** [comment]
Hi Binghui,

Thanks for mentioning this paper. Currently we are focusing on node-level attack and defense methods. For graph-level, we will develop them later. 

However, it seems that your are the author of this paper, so I am wondering if you could help develop the algorithm in this repository. You can create a pull request of your algorithm and we will process it.

Thank you.

**Comment by binghuiwang** [comment]
Hi Wei,

Thanks for your reply.  I need to clarify that our method is also focusing
on novel-level attack. Currently, our attack is implemented in C++, as it
is designed for very large-scale graph datasets. I will consider rewriting
it in python in the future.

thanks,
Binghui
