### ISSUE TITLE
Memory Requirement for running MetaApprox on Pubmed

### ISSUE THREAD

**Issue by BoyuanFeng** [DSE-MSU/DeepRobust#27]
Thanks for your wonderful work in "Graph Structure Learning for Robust Graph Neural Networks", KDD'20.

I am trying to repeat your results on Pubmed, especially the one based on mettack.

However, mettack requires large memory to run on Pubmed, such that it cannot fit into a GPU with 16GB memory.
I have also tried MetaApprox [1], but still facing similar problems.

1. Could you please share some experience on the memory requirement when you evaluate mettack?

2. You mentioned A-Meta-Self as the approximate version of meta-self, which saves memory and time. Is A-Meta-Self the same as the MetaApprox?

Thanks,
Boyuan

[1] https://github.com/DSE-MSU/DeepRobust/blob/master/deeprobust/graph/global_attack/mettack.py

**Comment by ChandlerBang** [comment]
Hi BoyuanFeng,

Thank you for your interest in our work!

Both metattack and Pro-GNN directly deal with dense matrix, which indicates they are not scalable for large graphs. 
1. For Pubmed, I used Tesla V100 (with 32 GB GPU memory) for the experiments for our model. But original mettack will still face memory issue so I turned to A-Meta-Self, as suggested in Table 8 of their paper https://openreview.net/pdf?id=Bylnx209YX. 
2. Yes, A-Meta-Self means MetaApprox with self-learning.

Hope this post can help you. Thanks again.

**Comment by BoyuanFeng** [comment]
Thanks for the quick update.

I am able to run MetaApprox on Pubmed now with a Tesla V100 (with 32 GB GPU memory). I am kind of surprised that MetaApprox uses 32396 MB out of 32510 MB on the Tesla V100.

In addition, could you please share some experience on, how long MetaApprox runs on Pubmed?
If I use the default setting (train_iter=100) and attack 20% edges for MetaApprox on Pubmed, it would take 2600 hours on Tesla V100...

**Comment by ChandlerBang** [comment]
I kind of forget about the detailed setting and it seems I used `train_iters=30`. It did not take me more than one day to finish generating 20% edges. So maybe you can try `train_iters=30`.

**Comment by BoyuanFeng** [comment]
Thanks for the information!

I was using the MetaApprox in DeepRobust. I will try the TensorFlow implementation.
