### ISSUE TITLE
Mistake in GGCL_D

### ISSUE THREAD

**Issue by marblet** [DSE-MSU/DeepRobust#31]
Thank you for developing this library!
I guess GGCL, which is a module for RGCN, has a mistake in the return variables of `forward` function.
In lines 69 - 72, graph/defense/rgcn.py, codes are written as:
```python
Att = torch.exp(-gamma * sigma)
mean_out = adj_norm1 @ (miu * Att)
sigma_out = adj_norm2 @ (sigma * Att * Att)
return mean_out, sigma
```
Currently `forward` returns sigma.
But I think `forward` should return sigma_out, i.e. sigma applied the attention `Att`
```python
Att = torch.exp(-gamma * sigma)
mean_out = adj_norm1 @ (miu * Att)
sigma_out = adj_norm2 @ (sigma * Att * Att)
return mean_out, sigma_out
```
If so, I will make a PR for this.
Thank you.

**Comment by ChandlerBang** [comment]
Yes, you are right. Please make a PR and I'll merge it.
Thanks for pointing it out.
