### ISSUE TITLE
error when use metaattack to attack feature

### ISSUE THREAD

**Issue by FFTYYY** [DSE-MSU/DeepRobust#40]
1.  if use sparce feature matrix: 'RuntimeError: add(sparse, dense) is not supported. Use add(dense, sparse) instead.'
2.  'Metattack' object has no attribute 'features_changes' I think you misspelled 'feature_change' as 'features_changes' in the code

**Comment by ChandlerBang** [comment]
Hi,
1. You are not supposed to use sparse matrix to generate feature perturbations as you need to compute gradients over all possible feature entries.
2. Can you provide more details for the exception traceback for this error? I cannot reproduce this error. In the current version of DeepRobust, it seems that 'Metattack' object does have the attribute 'features_changes'.

Thanks.

**Comment by FFTYYY** [comment]
code to reproduce the error:
```	import torch as tc
	import numpy as np
	from deeprobust.graph.data import Dataset
	from deeprobust.graph.defense import GCN
	from deeprobust.graph.global_attack import Metattack , MetaApprox
	from deeprobust.graph.utils import sparse_mx_to_torch_sparse_tensor

	data = Dataset(root = "/tmp/", name = "cora", setting = "nettack")
	adj, features, labels = data.adj, data.features, data.labels

	idx_train, idx_val, idx_test = data.idx_train, data.idx_val, data.idx_test
	idx_unlabeled = np.union1d(idx_val, idx_test)

	surrogate = GCN(nfeat = features.shape[1], nclass = labels.max().item()+1, nhid = 16, with_relu = False, device = 0).cuda()
	surrogate.fit(features, adj, labels, idx_train)

	features = sparse_mx_to_torch_sparse_tensor(features).to_dense()
	adj 	 = sparse_mx_to_torch_sparse_tensor(adj).to_dense()
	model = Metattack(model = surrogate, nnodes = adj.shape[0], feature_shape = features.shape, device = 0,
			attack_structure = False , attack_features=True).cuda()
	perturbations = int(0.002 * (features.shape[0] * features.shape[1]))

	model.attack(features, adj, labels, idx_train, idx_unlabeled, perturbations, ll_constraint = False)
	modified_features = model.modified_features
```
BTW, I searched 'features_changes' in deeprobust/graph/global_attack/mettack.py, only two results found, both look like `self.features_changes.data[row_idx][col_idx] += (-2 * modified_features[row_idx][col_idx] + 1)`.
it seems there is no assignment statement for this attribute. are you sure 'Metattack' object do have the attribute 'features_changes'?

**Comment by ChandlerBang** [comment]
Oh yes, you are right!  I've fixed that problem. Please see [commit](https://github.com/DSE-MSU/DeepRobust/commit/2b98aef0724f4d4c7337823f6476e69750c58bb7).

Thank you for pointing it out.
