### ISSUE TITLE
A potential bug in ig-attack

### ISSUE THREAD

**Issue by ForeverZyh** [DSE-MSU/DeepRobust#42]
https://github.com/DSE-MSU/DeepRobust/blob/16e6f0b003ab40c39bae9f954d7d37aa8a17048c/deeprobust/graph/targeted_attack/ig_attack.py#L120

If `self.attack_features == False` there is still a chance that ig_attack will attack features.
Suggested fix
```
if s_e[s_e_max] >= s_f[s_f_max] or not self.attack_features:
```

**Comment by ChandlerBang** [comment]
Hi,

Thanks for your comment. 

When `self.attack_structure` is `True` and `self.attack_features` is `False`,  the variable `s_f` will be all zero, as shown in 
https://github.com/DSE-MSU/DeepRobust/blob/16e6f0b003ab40c39bae9f954d7d37aa8a17048c/deeprobust/graph/targeted_attack/ig_attack.py#L110

Only when `s_e` are all negative (which means no possible perturbation can be made on the adjacency matrix) will the attacker choose to attack features. Personally I think this is unlikely to happen. Did you observe that when `self.attack_features == False`, ig_attack might attack features?

**Comment by ForeverZyh** [comment]
I am currently trying the `self.attack_features == False` setting. I have not observed this happened so far.

**Comment by ChandlerBang** [comment]
Well, as you mentioned,  it might be better to make some changes in this file.  I've just added some error messages for it.  Please see commit #https://github.com/DSE-MSU/DeepRobust/commit/276a7048aded2cf3a190d3851ffd4587b7d1dd49

Thank you for your suggestions.

**Comment by ForeverZyh** [comment]
Thanks for the effort!
