### ISSUE TITLE
Metattack, the forward of GCN is incorrect if `with_relu=True`

### ISSUE THREAD

**Issue by EdisonLeeeee** [DSE-MSU/DeepRobust#43]
https://github.com/DSE-MSU/DeepRobust/blob/276a7048aded2cf3a190d3851ffd4587b7d1dd49/deeprobust/graph/global_attack/mettack.py#L241-L252

https://github.com/DSE-MSU/DeepRobust/blob/276a7048aded2cf3a190d3851ffd4587b7d1dd49/deeprobust/graph/global_attack/mettack.py#L267-L277

It seems that the output of the last layer uses both `ReLU+Softmax` activation functions if `with_relu=True`.

**Comment by ChandlerBang** [comment]
Hi,

Thanks so much for your comment! I've fixed the issue in commit https://github.com/DSE-MSU/DeepRobust/commit/6d46c66a085fe4ee98c56e0306bd65cdcb7a7455.
