### ISSUE TITLE
Failed to load target_nodes.

### ISSUE THREAD

**Issue by shaolyy** [DSE-MSU/DeepRobust#44]
https://github.com/DSE-MSU/DeepRobust/blob/f473d0f0bf47c4a091058d32ecee4772481b5752/deeprobust/graph/data/attacked_data.py#L126-L143

Should L127 be before L126? Otherwise, `self.target_nodes` will always be None.

**Comment by ChandlerBang** [comment]
Hi  #shaolyy,

Thank you so much for pointing it out! I've just fixed that issue and pulled a commit https://github.com/DSE-MSU/DeepRobust/commit/d4ebe2d22d2378335f7558a1389dd3e13910fbb2

**Comment by shaolyy** [comment]
It's my pleasure.
