### ISSUE TITLE
Topology Attack also considers main diagonal (twice)

### ISSUE THREAD

**Issue by sigeisler** [DSE-MSU/DeepRobust#46]
Hi,

I fear there is an issue with the [topology attack](https://github.com/DSE-MSU/DeepRobust/blob/master/deeprobust/graph/global_attack/topology_attack.py). From what I understand you initialize as many elements in `self.adj_changes` as the upper half of the adjacency matrix without the main diagonal. I agree that this is correct. However, in [get_modified_adj(...)](https://github.com/DSE-MSU/DeepRobust/blob/master/deeprobust/graph/global_attack/topology_attack.py#L183) you get the indices including the main diagonal but exclude the node with the highest index. I believe `tril_indices = torch.tril_indices(row=self.n, col=self.n, offset=-1)` should fix it.

**Comment by ChandlerBang** [comment]
Thank you so much! That is a very crucial point!

I've just fixed it.
