### ISSUE TITLE
ModuleNotFoundError: No module named 'node2vec'

### ISSUE THREAD

**Issue by EdisonLeeeee** [DSE-MSU/DeepRobust#49]
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-ab061214f9c6> in <module>
      7 import torch.optim as optim
      8 from deeprobust.graph.utils import accuracy
----> 9 from deeprobust.graph.defense.pgd import PGD, prox_operators
     10 import warnings
     11 

~/DeepRobust/deeprobust/graph/defense/__init__.py in <module>
      4 from .prognn import ProGNN
      5 from .simpgcn import SimPGCN
----> 6 from .node_embedding import Node2Vec, DeepWalk
      7 import warnings
      8 try:

~/DeepRobust/deeprobust/graph/defense/node_embedding.py in <module>
     16 from sklearn.preprocessing import normalize
     17 from sklearn.metrics import f1_score, roc_auc_score, average_precision_score, accuracy_score
---> 18 from node2vec import Node2Vec as N2V
     19 
     20 class BaseEmbedding:

ModuleNotFoundError: No module named 'node2vec'
```
Hi, is there a missing file `node2vec`?

**Comment by EdisonLeeeee** [comment]
Comment out this line of code can fix the issue.

**Comment by ChandlerBang** [comment]
Hi, just “pip install node2vec”. See details in [requirements.txt](https://github.com/DSE-MSU/DeepRobust/blob/master/requirements.txt)

**Comment by EdisonLeeeee** [comment]
Hi, Wei Jin.

Thanks, it works.
The implementation of [node2vec](https://github.com/eliorc/node2vec/blob/master/node2vec/node2vec.py)  is much slower and the `sp.csr_matrix` needs to be transformed into `nx.Graph`.
I think it's necessary to implement Node2Vec in deeprobust.

**Comment by ChandlerBang** [comment]
Yeah, I totally agree. The current model serves as a temporary solution and I shall implement it in the future. Currently I am working on adding graph classification and several other attack/defense methods.

Thank you for your suggestion.

**Comment by EdisonLeeeee** [comment]
I can help you implement this :), just wait a moment.

**Comment by EdisonLeeeee** [comment]
Kindly refer to https://github.com/DSE-MSU/DeepRobust/pull/51

**Comment by ChandlerBang** [comment]
Thank you so much!!!!
