### ISSUE TITLE
Cannot load cora-ml with 15% and 20% perturbation rate

### ISSUE THREAD

**Issue by liu-jc** [DSE-MSU/DeepRobust#52]
Hi,

I found we cannot load cora-ml datasets with 15% and 20% perturbation rate when I am trying to run [test_sgc.py](https://github.com/DSE-MSU/DeepRobust/blob/master/examples/graph/test_sgc.py). The problem is that we cannot find `cora_ml_meta_adj_0.15.npz` and `cora_ml_meta_adj_0.2.np` in the github repo [Pro-GNN](https://github.com/ChandlerBang/Pro-GNN/tree/master/meta). As you are from the same research group, I just open an issue here. Hope these two perturbed graphs can be uploaded there. Then the problem will be resolved and it will make the example more complete. Thanks in advance.

**Comment by ChandlerBang** [comment]
Hi,

Thanks for the comment. I redid the attacks (0.5, 0.1, 0.15, 0.2, 0.25 perturbation rates) and uploaded the data to [Pro-GNN](https://github.com/ChandlerBang/Pro-GNN/tree/master/meta). Note that the graphs under 0.05/0.1/0.25 perturbation rates are also different from previous ones.

**Comment by liu-jc** [comment]
Great! Thank you Wei Jin.

Regards,
Juncheng

**Comment by liu-jc** [comment]
> Hi,
> 
> Thanks for the comment. I redid the attacks (0.5, 0.1, 0.15, 0.2, 0.25 perturbation rates) and uploaded the data to [Pro-GNN](https://github.com/ChandlerBang/Pro-GNN/tree/master/meta). Note that the graphs under 0.05/0.1/0.25 perturbation rates are also different from previous ones.
Hi Wei Jin, 

I use SGC and GCN on the dataset with 0.25 perturbation rate. The test accuracies are both larger than 60%. On the dataset with 0.2 and 0.15 perturbation rates, the accuracies are usually less than 60%. I think it's quite strange. Could you check it? Maybe there're some mistakes?

**Comment by ChandlerBang** [comment]
Please remove the original files of the perturbed graphs. For example, if you stored them in "/tmp", you should remove /tmp/cora_ml_meta_adj_0.25.npz or `rm /tmp/cora_ml_meta_*`.

**Comment by liu-jc** [comment]
> Please remove the original files of the perturbed graphs. For example, if you stored them in "/tmp", you should remove /tmp/cora_ml_meta_adj_0.25.npz or `rm /tmp/cora_ml_meta_*`.

Thanks. Now all look good!
