### ISSUE TITLE
Is dataset.py not compatible with prognn?

### ISSUE THREAD

**Issue by cloudzs** [DSE-MSU/DeepRobust#58]

**Comment by ChandlerBang** [comment]
If you are using the lasted code, you can specify `setting='prognn'` in `Dataset()` to get the data splits used in ProGNN.
`data = Dataset(root='/tmp/', name='cora', setting='prognn')`

If you wanna know more about how ProGNN generates the splits, please take a look at the [script](https://github.com/ChandlerBang/Pro-GNN/blob/master/save_splits.py).

**Comment by cloudzs** [comment]
I guess it's because the it's the setup.py import deeprobust-0.2.0😂

**Comment by cloudzs** [comment]
Thank you. Wei

**Comment by ChandlerBang** [comment]
You're welcome :)
