### ISSUE TITLE
These is always a bug : 'numpy.ndarray' object has no attribute 'A1'

### ISSUE THREAD

**Issue by forechoandlook** [DSE-MSU/DeepRobust#59]
![image](https://user-images.githubusercontent.com/50866639/118777269-766a3880-b8bb-11eb-9d98-a36c16366f7f.png)

**Comment by EdisonLeeeee** [comment]
Maybe your `adj` is a numpy array instead of a scipy sparse matrix?

**Comment by forechoandlook** [comment]
You mean that `adj` should be a scipy sparse matrix?

**Comment by EdisonLeeeee** [comment]
Yes, it must be.

**Comment by forechoandlook** [comment]
Ok, I will try! Thanks!

**Comment by ChandlerBang** [comment]
Hi, thank you, EdisonLeeeee . But the bug happens at `self.feature_scores()`. So that means the feature matrix should be a scipy sparse matrix.

**Comment by EdisonLeeeee** [comment]
You are absolutely right.

**Comment by pqypq** [comment]
Hi!
I made some modifications to use the "scipy.sparse.csr_matrix" function to make the "X_influencers" to be a scipy sparse matrix. However, when I run the polblogs dataset, I still got the error `AttributeError: 'numpy.ndarray' object has no attribute 'A1'`
Can you give some suggestions for solving this problem?
Thanks
