### ISSUE TITLE
scikit_learn --> scikit-learn ?

### ISSUE THREAD

**Issue by achangeo** [DSE-MSU/DeepRobust#61]
Thinking this may be an error. Not finding it on pypi but found https://pypi.org/project/scikit-learn/ 

https://github.com/DSE-MSU/DeepRobust/blob/6a392188fb586155161db707756f4255760d6f5c/requirements.txt#L11

https://github.com/DSE-MSU/DeepRobust/blob/master/setup.py#L28

**Comment by ChandlerBang** [comment]
hmmm, I just tried `pip install scikit_learn==0.22.1` and it works fine for me...

**Comment by ChandlerBang** [comment]
Will it throw an error if you run the command above?

**Comment by achangeo** [comment]
Not an actual error I misspoke. Saw it referred to in official documentation more as the hyphenated name and wanted to point it out is all!

**Comment by ChandlerBang** [comment]
Ok, I've updated it. Thanks!
