### ISSUE TITLE
Question on the symmetric constraint in ProGNN

### ISSUE THREAD

**Issue by Ononoki-Yotsugi** [DSE-MSU/DeepRobust#73]
Hi, Thanks for sharing the DeepRobust code.
I've been studying the code of ProGNN. There is a operation for the symmetric constraint: 
![image](https://user-images.githubusercontent.com/60538191/127665974-fd8e7c3f-8d90-44e3-9f13-d1c502878374.png)
I noticed that in _EstimateAdj_ in *ProGNN.py*, the process is realized by:
`if self.symmetric:
            adj = (self.estimated_adj + self.estimated_adj.t())`

It seems that 2 is missing. Is this a mistake or a design？

**Comment by ChandlerBang** [comment]
Hi, thanks for pointing this inconsistency out. It should be `adj = (self.estimated_adj + self.estimated_adj.t())/2` and I have just fixed the issue. I also need to note that the default Pro-GNN hyper-parameter setting does not exert the symmetric constraint; so it does not affect the reported performance.

**Comment by Ononoki-Yotsugi** [comment]
Got it. But why doesn't the defualt setting exert the symmetric constraint,? It seems different from the paper. What effects will it have if using the constraint.

**Comment by ChandlerBang** [comment]
We treat this constraint as a hyper-parameter. And it turns out that without this constraint the performance is better.

**Comment by Ononoki-Yotsugi** [comment]
Got it. Thanks.
