### ISSUE TITLE
Support Running GNNs on Specific GPU

### ISSUE THREAD

**Issue by LFhase** [DSE-MSU/DeepRobust#74]
Hi DeepRobust Team,

I've encountered a problem when testing GNNs on devices other than `cuda:0`. To reproduce, simply modifying line 18 in  `test_gcn.py` to 
```
device = torch.device("cuda:2" if torch.cuda.is_available() else "cpu")
```
Then the error message is prompted as follows:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices
```

I found it's caused by `normalize_adj_tensor` and `degree_normalize_adj_tensor`, where the device is set to be `cuda:0` by default wherever adj is. Though many people run experiments on `cuda:0` by default, it could be even better to support running GNNs in DeepRobust on other devices specified via the `device` variable. 

Could you add this feature in the next update? Thank you. 😀

**Comment by ChandlerBang** [comment]
Hi, thanks for reporting a potential issue! I just checked the code but I found it is 'cuda' instead of `cuda:0` in `normalize_adj_tensor` and `degree_normalize_adj_tensor`. So I think it should not throw an error. Could you provide more details on your bug?

https://github.com/DSE-MSU/DeepRobust/blob/2a52969fb8b881ac5325a8d0a26a6880aa8b6a9b/deeprobust/graph/utils.py#L257-L266

https://github.com/DSE-MSU/DeepRobust/blob/2a52969fb8b881ac5325a8d0a26a6880aa8b6a9b/deeprobust/graph/utils.py#L202-L213.

**Comment by EdisonLeeeee** [comment]
By default, `torch.device("cuda")` is equivalent to `torch.device("cuda:0")` and maybe this is the point :).

**Comment by LFhase** [comment]
Hi @ChandlerBang,

I agree with @EdisonLeeeee 's point. 

Specifically, if `adj`  is at somewhere else than `cuda:0`, e.g., `cuda:1`, then after these two functions, the returned `adj` would be at `cuda:0` and leads to some potential issues.

Could you double-check with it again? Thank you. 😀

**Comment by ChandlerBang** [comment]
Thank you @EdisonLeeeee and @LFhase for the comments. 

I see your point now. I would suggest to use `CUDA_VISIBLE_DEVICES=2` before your command and it looks like `CUDA_VISIBLE_DEVICES=2 python test_gcn.py`.

**Comment by EdisonLeeeee** [comment]
@ChandlerBang I think it would be better to replace
```python
device = torch.device("cuda" if adj.is_cuda else "cpu") 
```
with
```python
device = adj.device
```
And it would also solve @LFhase 's problem.

**Comment by LFhase** [comment]
Thank you @ChandlerBang and @EdisonLeeeee. I think @EdisonLeeeee 's solution would be a feasible approach if `adj.device` can be always accessed in each call of the two functions. 

BTW, I don't have further questions. 😃

**Comment by ChandlerBang** [comment]
Sorry for the late reply. I have just fixed the issue. Thank you @LFhase  and @EdisonLeeeee !
