### ISSUE TITLE
I am having trouble with an error that prevents me from accessing the dataset.

### ISSUE THREAD

**Issue by katsuki-uuu** [DSE-MSU/DeepRobust#78]
Hello.

I downloaded all the code from this site to my desktop and ran the following

examples/graph/test_mettack.py --dataset cora --ptb_rate 0.05

However, I got the following error

Traceback (most recent call last):
  File "test_mettack.py", line 39, in <module
    data = Dataset(root='/tmp/', name=args.dataset, setting='nettack')
  File "C:\ Users\uno\anaconda3\envs\GAN_torch\lib\site_packages\deeprobust\graph\data\dataset.py", line 70, in __init__
    self.adj, self.features, self.labels = self.load_data()
  File "C:\ Users\uno\anaconda3\envs\GAN_torch\lib\site_packages\deeprobust\graph\data\dataset.py", line 113, in load_data
    self.download_npz()
  File "C:\ Users\uno\anaconda3\envs\GAN_torch\lib\site_packages\deeprobust\graph\data\dataset.py", line 134, in download_npz
    raise Exception('''Download failed! Make sure you have a stable Internet connection and enter the right name'')
Exception: Download failed! Make sure you have a stable Internet connection and enter the right name

I can't seem to access the dataset, how can I improve this?
Please let me know if there is a way to download the dataset to my desktop.

Thank you.

**Comment by ChandlerBang** [comment]
The program should print 
> Downloading from https://raw.githubusercontent.com/danielzuegner/gnn-meta-attack/master/data/cora.npz to /tmp/cora.npz

Did you observe it?  If you observe it, it could be the reason that 
(1) the folder (e.g., `/tmp/` in my case) you specified does not exist. 
(2) your internet connection failed. You can directly try accessing the website `https://raw.githubusercontent.com/danielzuegner/gnn-meta-attack/master/data/cora.npz` to see if you can download.

**Comment by katsuki-uuu** [comment]
Thank you.

I downloaded the file directly from your URL because there was no /tmp/ folder and I could not connect to the Internet due to VPN.

I replaced "root" in line 39 of test_mettack.py with the destination, but it did not work.

What else do I need to change?
If possible, I would like to load the data in my directory.

**Comment by Initiator-Z** [comment]
For my case I'm pretty sure theres' no problem with the internet connection. All I did is creating the 'tmp' folder in the directory and change the root('/tmp/) to (./tmp/) and then it seems to be working.

**Comment by katsuki-uuu** [comment]
Thank you for your answer.
It worked fine.
