### ISSUE TITLE
I want to try mettack with my own data set.

### ISSUE THREAD

**Issue by katsuki-uuu** [DSE-MSU/DeepRobust#83]
I'm sorry to keep repeating this.
I want to try an attack with my own dataset in cora dataset format, how do I save the dataset as npz?

I don't know the contents of the cora.npz array, so I don't know how to create the dataset.

Thank you.

**Comment by katsuki-uuu** [comment]
Thank you.
However, it saves the file in npz format, separating it into "mod_adj" and "mod_feature".
I would like to save my data in exactly the same format as "cora.npz" and use it as training data for mettack.
I don't know how the adj, features and labels are stored as arrays in "cora.npz", so I don't know how to process my data set as in "cora.npz".

I think that if I can save my data as "cora.npz", I can easily train "mettack" with my data.

**Comment by katsuki-uuu** [comment]
Thank you.

That's not what I'm talking about.
However, I will study it again.

**Comment by ChandlerBang** [comment]
I mean, you can try to use `np.save` to store an array of (adj, features, labels).

**Comment by katsuki-uuu** [comment]
Thank you.
I try it.
