### ISSUE TITLE
[Bug] x.zero_grad() will result in "AttributeError: 'Tensor' object has no attribute 'zero_grad'"

### ISSUE THREAD

**Issue by zhjwy9343** [DSE-MSU/DeepRobust#89]
In the # 105 of deeprobust/image/attack/deepfool.py. The code was change from zero_gradients(x) to x.zero_grad(), which will cause the "AttributeError: 'Tensor' object has no attribute 'zero_grad'" error in Pytorch 1.10, 1.9, 1.8, 1.7.

**Comment by jsrdcht** [comment]
Do you still preserve the mistake? Try `x.grad.zero_()`, I think it may work.
